services:
  - type: web
    name: pm-dash-backend
    env: docker
    dockerfilePath: Dockerfile
    branch: main
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: proquo.techDB
          property: connectionString
    autoDeploy: true
